services:
  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5050:5050"

  company-service:
    build:
      context: ./server/services/company-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/attendify
      JWT_SECRET: jeetxmurli
      PORT: 3001
      RABBITMQ_URI: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - redis
      - mongodb

  email-service:
    build:
      context: ./server/services/email-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      RABBITMQ_URI: amqp://rabbitmq
      EMAIL_USER: dorothea.grady99@ethereal.email
      EMAIL_PASS: REt4NxVNBNbbap9jSR
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
     test: ["CMD", "rabbitmqctl", "ping"]
     interval: 10s
     timeout: 10s
     retries: 5


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
