services:
  company-service:
    build:
      context: ./server/services/company-service
      dockerfile: Dockerfile
    ports:
      - "3001:2929"
    environment:
      MONGO_URI: mongodb://localhost:27017/attendify
      JWT_SECRET: jeetxmurli
      PORT: 3001
      RABBITMQ_URI: amqp://rabbitmq
    depends_on:
      - rabbitmq
      - redis
      - mongo

  email-service:
    build:
      context: ./server/services/email-service
      dockerfile: Dockerfile
    ports:
      - "3002:2929"
    environment:
      PORT: 3001
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mongo:
      image: mongo
